updates.ignore = [ { groupId = "uk.gov.nationalarchives", artifactId = "consignment-api-db" } ]
pullRequests.grouping = [ { name = "all", "filter" = [{"group" = "*"}]} ]
updates.pin = [ { groupId = "org.scala-sbt", artifactId = "sbt" version="1."} ]
