name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    environment: integration
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.MANAGEMENT_ACCOUNT }}:role/GithubActionsTest
          aws-region: eu-west-2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - name: Build and Test
        run: sbt test scalastyle test:scalastyle 'graphqlValidateSchema "build" "consignmentApi"'